# Generated by Django 4.1.2 on 2022-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_checkout_companyname_alter_checkout_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='companyname',
            field=models.CharField(default='', max_length=70, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(default='', max_length=45, verbose_name='country name'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.CharField(default='', max_length=45, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='firstname',
            field=models.CharField(default='', max_length=12, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='lastname',
            field=models.CharField(default='', max_length=15, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.PositiveIntegerField(default='', verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(default='', max_length=15, verbose_name='state name'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='town',
            field=models.CharField(default='', max_length=157, verbose_name='town name'),
        ),
    ]
